spelunky-fyi/overlunky

.github/workflows/build.yml
Cargo.lock
crates/injected/Cargo.toml

automatic release build per tags

GitHub Actions for building binaries

---

src/injected/ui.cpp

* Provides a table to access entity names. table is named `ENT_TYPE`
with entries named such as `ITEM_BOMB`.
* Pulled in patch from iojon to only re-execute script if it was updated
in the UI
* Added new function called `setinterval` which takes a callback and
milliseconds for how frequently to execute the callback.

Adds some additional fixes/support for Lua

---

src/injector/injector.cpp

Make library search case insensitive

---

src/game_api/CMakeLists.txt
src/game_api/window_api.cpp
src/game_api/window_api.hpp
src/injected/main.cpp
src/injected/ui.cpp
src/injected/ui.hpp

Raw input breaks with this PR, hence it's WIP. But I don't know how that is supposed to work so it's difficult to debug.
Other than that it seems to fix alt-tab and changing to fullscreen. Plus it moves the imgui and dx11 hooks to game_api so that Playlunky can eventually profit from it.

Refactor of dx11 and window hooks

---

src/spel2_dll/spel2.cpp
src/spel2_dll/spel2.h

Script message on dll interface

---

src/spel2_dll/spel2.cpp
src/spel2_dll/spel2.h

Add access to script meta data in dll interface

---

docs/script-api.md
examples/vlads_cape.lua
src/game_api/movable.hpp
src/game_api/script.cpp

Now we can make Flappy Bird in Spelunky 2!

reveng cape and vlad's cape

---

src/game_api/script.cpp
src/game_api/window_api.cpp
src/game_api/window_api.hpp
src/injected/ui.cpp
src/spel2_dll/spel2.cpp
src/spel2_dll/spel2.h

Makes show cursor and hide cursor on the dll interface work with the lua window api
Move the mouse activity logic to dynamically hide cursor to window_api

Improve api for mouse cursor

---

docs/script-api.md
src/game_api/entity.cpp
src/game_api/entity.hpp
src/game_api/movable.hpp
src/game_api/rpc.cpp
src/game_api/rpc.hpp
src/game_api/script.cpp

- add method to the Player to query current amount of blood inside the Kapala
- set_kapala_blood_threshold: change the amount of blood needed for a health increase
- set_kapala_hud_icon: choose which icon is to be displayed for the Kapala in the hud

rev eng kapala

---

src/game_api/entity.hpp
src/game_api/script.cpp

Add draw_depth to EntityDB

---

docs/script-api.md

Updates script-api.md to make the location of the overlunky.ini file more clear.

updates docs to clarify overlunky.ini location

---

docs/generate.py

@Malacath-92 mentioned that I should update the generate.py as part of my docs update
so I'm doing that: https://github.com/spelunky-fyi/overlunky/pull/60

update generate.py to make overlunky.ini path more clear

---

docs/script-api.md
src/game_api/script.cpp

Please ignore my other commits that have to do with save_data and load_data. Those changes should not be in this PR.

Add click_position to lua api as game_position

---

docs/script-api.md
examples/inventory.lua
src/game_api/rpc.cpp
src/game_api/rpc.hpp
src/game_api/script.cpp

entity_get_items_by accesses the inventory of a uid
with an item filter and a mask filter.
Added inventory.lua as an example.

Adds script api: entity_get_items_by

---

CMakeLists.txt
src/game_api/sound_manager.cpp
src/injected/CMakeLists.txt

What the title says. I palyed ~30min with Pot+Enemy randomizer and I saw no problem. What other stuff can I test?

Enable C++20 support

---

.vscode/lua-api.code-snippets

Adds some simple quality of life snippets for VS Code.

Code snippets for lua

---

docs/generate.py
docs/script-api.md
src/CMakeLists.txt
src/injector/CMakeLists.txt

Wanna fix the doc bugs that people keep mentioning.

Add a target for generating docs and all the game data stuff

---

examples/guns.lua

also works for more the one player now

Update the gun example

---

examples/rando/trap.lua
examples/reverse.lua

I decided I'd fix a few example scripts.

Fixing a few example scripts

---

docs/entities-hierarchy.md
src/game_api/entities_items.hpp
src/game_api/script/usertypes/entities_items_lua.cpp
src/game_api/script/usertypes/entity_casting_lua.cpp

I assume this is the same size as the Teleporter field

Add TeleporterBackpack (aka Telepack)

---

src/game_api/script/events.cpp

Fix speech bubble and toast not showing up when there is no scripts

---

src/game_api/level_api.cpp

This lets multiple tilecode names to map to the same tile code.

Add tilecode aliases

---

src/game_api/entities_activefloors.cpp
src/game_api/entities_floors.cpp
src/game_api/entity.cpp
src/game_api/layer.hpp
src/game_api/math.hpp
src/game_api/rpc.cpp
src/injected/ui.cpp

@Mr-Auto if you can check that I didn't break anything

Post pr suggestions

---

docs/game_data/spel2.lua
examples/drawing.lua
src/game_api/script/usertypes/gui_lua.cpp
src/game_api/script/usertypes/gui_lua.hpp

more drawing functions from imgui

---

src/game_api/layer.hpp
src/game_api/script/lua_vm.cpp
src/game_api/strings.cpp

Draft for now, maybe I'll think of some more

More const values

---

src/game_api/entity.cpp
src/game_api/render_api.cpp
src/game_api/script/lua_backend.cpp
src/game_api/spawn_api.cpp
src/game_api/texture.cpp
src/injected/ui.cpp

Fixing issue #217
Fixing `spawn_mushroom` for use as a tilecode mentioned on discord
Fixing callbacks issue from discord

Fixing stuff

---

examples/waddler_storage.lua
src/game_api/entities_floors.cpp
src/game_api/entity.cpp
src/game_api/entity.hpp
src/game_api/script/usertypes/state_lua.cpp
src/injected/ui.cpp
src/injected/ui.hpp
src/injected/ui_util.cpp
src/injected/ui_util.hpp

This feel like this has been on my todo list for years!

Entity finder, drawing tools

---

src/game_api/rpc.cpp
src/game_api/rpc.hpp
src/injected/ui.cpp
src/injected/ui_util.cpp
src/injected/ui_util.hpp

…also fix crash with `activate_sparktraps_hack` + `modify_sparktraps`

Fix circle drawn for SparkTraps with drawn hitboxes option

---

docs/game_data/spel2.lua
docs/parse_source.py
docs/src/includes/_types.md
src/game_api/script/usertypes/entities_chars_lua.cpp
src/game_api/script/usertypes/entities_floors_lua.cpp
src/game_api/script/usertypes/entities_items_lua.cpp
src/game_api/script/usertypes/entity_lua.cpp
src/game_api/script/usertypes/game_manager_lua.cpp
src/game_api/script/usertypes/gui_lua.cpp
src/game_api/script/usertypes/level_lua.cpp
src/game_api/script/usertypes/particles_lua.cpp
src/game_api/script/usertypes/screen_arena_lua.cpp
src/game_api/script/usertypes/screen_lua.cpp
src/game_api/script/usertypes/state_lua.cpp
src/game_api/script/usertypes/vanilla_render_lua.cpp

And add terrible autodoc support, but at least it seemed to somehow only fix some missing stuff.
Doing this to huge usertype bindings might affect performance, but I don't even know which way. At least it should help with running out of heap space?

Convert arbitrary usertypes to runtime binding

---

src/game_api/search.cpp

Didn't test everything so draft
btw. that pattern was just meant to break, as it included relative offset
This pattern fix makes it work on previews version as well, ~~not sure about the vtable offsets and stuff~~

Game update

---

examples/skins.lua
src/game_api/file_api.cpp
src/game_api/file_api.hpp
src/game_api/screen.hpp
src/game_api/script/lua_backend.cpp
src/game_api/script/lua_console.cpp
src/game_api/script/lua_vm.cpp
src/game_api/script/script_impl.cpp
src/game_api/script/usertypes/gui_lua.cpp
src/game_api/script/usertypes/gui_lua.hpp
src/game_api/script/usertypes/prng_lua.cpp
src/game_api/script/usertypes/texture_lua.cpp
src/injected/ui.cpp
src/shared/logger.h

- Misc (UI) bugfixes
- Added `unregister_option` to remove options
- Added `get_local_[state/players/prng]` for the local-thread version of those
- Added `get_image_size` to get dimensions of image files
- Added `list_dir` to list files from mod subfolder and `list_char_mods` all character mods from packs
- Added ability to load image files with "absolute" path (relative to game folder)
- Added binding for ImGui::ImageButton
- Added `create_image_crop` to load ImGui images cropped
- Added TooManySkins script to use any installed character mods (from the character select or pause menu by pressing whip)

Random fixes and Too Many Skins

---

docs/game_data/spel2.lua
docs/src/includes/_types.md
src/game_api/script/usertypes/gui_lua.cpp

still shows `ImVec2` instead of `Vec2` for some reason

Fix `ImGuiIO`

---

src/injected/ui.cpp
src/injected/ui_util.cpp
src/injected/ui_util.hpp

Testing a little UI toy I always wanted to make that nobody probably needs 🤷🏻‍♂️ 
1. Go to the Void with Alt+V and build something OR select some entities with Alt+M3
2. Export the contraption to clipboard as string with Ctrl+E
3. Import and play it from clipboard with Ctrl+V
Some random thing to paste, simply Ctrl+V to the game:
```
V11278691374000g0F77002u1077002u1177002u1277002u1377002u1477002u1577000f0F76000f0F75000f0F7400040F73000410730004137300041473000415730004167300041777002u1877002u187600041773002u187300040F7200041072000414720004157200041672001s1874001s1774001s1674001s157400141776011410760014107500
```

Serialize and copy level contents thing

---

README.md
src/injected/ui.cpp

Add spawner Hotbar

---

docs/game_data/spel2.lua
docs/generate_emmylua.py

- Fix that overloaded methods weren't getting any autocompletion.
- Fixed a small bug
- Include static class functions

Emmylua overload fix, static class functions

---

docs/game_data/spel2.lua
docs/generate.py
docs/src/includes/_enums.md
docs/src/includes/_types.md
src/game_api/script/lua_vm.cpp
src/game_api/script/usertypes/state_lua.cpp
src/game_api/state.hpp
src/game_api/state_structs.hpp

This PR exposes journal progress fields. These are the stickers, stains, and themes that appear on the journal progress page during and after a run.

Expose journal fields

---

docs/game_data/spel2.lua
docs/src/includes/_globals.md
src/game_api/file_api.cpp
src/game_api/level_api.cpp
src/game_api/render_api.cpp
src/game_api/script/lua_backend.cpp
src/game_api/script/lua_vm.cpp
src/game_api/script/usertypes/entity_lua.cpp
src/game_api/script/usertypes/gui_lua.cpp
src/game_api/script/usertypes/vanilla_render_lua.cpp
src/game_api/string_hashes.cpp
src/game_api/strings_get_hashes.py

Just to be clear, the main change is in `lua_vm.cpp`

fix set_interval

---

src/game_api/script/usertypes/socket_lua.cpp
src/game_api/script/usertypes/socket_lua.hpp

```lua
http_get_async("https://mossranking.com/api/getwr.php?cat=201", function(res, err)
if res then
local wr = json.decode(res)
prinspect(wr)
elseif err then
prinspect(err)
end
end)
```
`{ "S̼̼ͪh͚͚ͯa͔͔ͩd̶̵ow", "81250", "1:21.250", "2023-08-05" }`

Add http GET api

---

docs/game_data/spel2.lua
docs/generate.py
docs/src/includes/_globals.md
docs/src/includes/_home.md
src/game_api/lua_libs/lua_libs.cpp
src/game_api/script/lua_console.cpp
src/game_api/script/lua_vm.cpp

I think this is better than "<userdata 1>"

Better console output

---

src/game_api/script/lua_backend.cpp
src/game_api/script/lua_backend.hpp
src/game_api/script/lua_vm.cpp

Fix infinite loop detection again

---

.github/workflows/build.yml
.github/workflows/continous_integration.yml
.github/workflows/whip-build.yml
src/CMakeLists.txt

Lets see if this workflow workaround works. Also updates sol2 to 3.3.0 and lua to 5.4.6, why not.

Another fix and update

---

docs/game_data/spel2.lua
docs/src/includes/_types.md
src/game_api/game_api.hpp
src/game_api/game_manager.hpp
src/game_api/screen.hpp
src/game_api/script/usertypes/screen_lua.cpp
src/game_api/script/usertypes/state_lua.cpp
src/game_api/state.hpp

Some leftovers from failed attempts at accessing the actual inputs in the game
Since i wrote down at least some of the variables types decide to make pr

Some Screens and GameAPI stuff

---

src/game_api/window_api.cpp

I guess I have to do this now that it's building again...
I think it works on the latest but also ancient gameoverlayrenderer64.dlls.

Fix steam overlay hook patterns

---

src/game_api/online.hpp
src/game_api/script/usertypes/state_lua.cpp

add fields to `OnlinePlayer`
- player_name_length
- id
- game_mode
- ready_state
- platform
expose `game_mode`, `ready_state`, `platform` fields to lua
add enums and expose to lua
- GAME_MODE(COOP, ARENA)
- READY_STATE(NOT_READY, READY, SEARCHING)
- PLATFORM(NONE, DISCORD, STEAM, XBOX, SWITCH, PLAYSTATION)

add field of online player, enums

---

.github/workflows/build-docs.yml
.github/workflows/docs_verify.yml
.github/workflows/whip-build.yml

Fixes parts of #403, however to fix the set-output warning we'd have to use a different action

Fix some Actions warnings

---

docs/game_data/spel2.lua
docs/src/includes/_types.md
src/game_api/entity.cpp
src/game_api/entity.hpp
src/game_api/illumination.cpp
src/game_api/script/usertypes/entity_lua.cpp

Fix `abs_position` being wrong in certain frame/sub frame situations
