- src/game_api/sound_manager.cpp
- src/injected/decode_audio_file.cpp
This fixes a bug where fmod reads/writes out of the allocated buffer and sometimes that breaks audio, especially for short audio.
> Add 16 bytes of padding to audio according to the FMOD docs

- src/game_api/script/script_impl.cpp
- src/game_api/script/usertypes/gui_lua.cpp
New version of imgui crashes when a NaN is passed to one of the
arguments. The codepath that found this crash was to first measure
the text height when in fullscreen mode while alt-tabbed and then
feeding the output into draw_text.
Test Script:
```lua
set_callback(function()
local x = 0
local size = 24
local text = "X"
-- setting y directly won't cause a crash
--local y = -0.5
-- but using y as the result of a text_size causes a crash
local text_w, text_height = draw_text_size(size, text)
local y = text_height
draw_rect(x, y, x+1, y, 2, 0, rgba(255,255,255,255))
end, ON.GUIFRAME)
```
Also updates imgui to latest in the docking branch
> Adds NaN checks to crashing imgui draw functions

- .gitignore
- src/game_api/entities_items.hpp
- src/game_api/entity.cpp
- src/game_api/entity.hpp
- src/game_api/movable.hpp
- src/game_api/script/lua_backend.cpp
- src/game_api/script/lua_backend.hpp
- src/game_api/script/lua_vm.cpp
After adding warps the timers were not cleared cause the screen never changes. Also the checks in onlevel were always a bit janky and I think they only worked 99.5%.
I think state.loading should work for both. Does this make more sense?
Also returning false from interval to clear it sounds neat as in #78
> Clear timers on warp, make level callbacks better

- src/game_api/state.cpp
When uid is -1, `uid+1` is 0 of course. The output of `lowbias32(0)` is 0. This conflicts with the use of 0 to indicate that the robin-hood table entry has been deleted.
> Special-case -1 in State::find()

- docs/examples/spawn_roomowner.lua
- docs/examples/spawn_shopkeeper.lua
- examples/room_visualizer.lua
- src/game_api/script/lua_vm.cpp
- src/game_api/spawn_api.cpp
- src/game_api/spawn_api.hpp
This seems to work, would probably work for the other roomowners too.
Makes a shotgun shop where you're standing:
```lua
local x, y, l = get_position(get_player(1).uid)
add_item_to_shop(spawn_on_floor(ENT_TYPE.ITEM_SHOTGUN, x-1, y, l), spawn_shopkeeper(x+1, y, l))
```
Waddler selling puppies
```lua
local x, y, l = get_position(get_player(1).uid)
local owner = spawn_roomowner(ENT_TYPE.MONS_STORAGEGUY, x+1, y, l, ROOM_TEMPLATE.SHOP)
add_item_to_shop(spawn_on_floor(ENT_TYPE.MONS_PET_DOG, x-1, y, l), owner)
add_item_to_shop(spawn_on_floor(ENT_TYPE.MONS_PET_DOG, x-2, y, l), owner)
add_item_to_shop(spawn_on_floor(ENT_TYPE.MONS_PET_DOG, x-3, y, l), owner)
```
> add spawn_shopkeeper to make shops anywhere

- src/game_api/script/lua_vm.cpp
> Return the callback id from pre_statemachine callback so that they can later be cleared.

- src/game_api/script/lua_backend.cpp
Fix the TOAST and SPEECH_BUBBLE callbacks to continue running when the first one returns nil, and also to honor the promise made in the comment that all registered callbacks will be executed but only the first to return a value will actually matter.
> Fix the TOAST and SPEECH_BUBBLE callbacks

- src/game_api/rpc.cpp
- src/game_api/rpc.hpp
- src/game_api/script/lua_vm.cpp
- src/game_api/script/usertypes/state_lua.cpp
- src/game_api/search.cpp
Simply using `storage_floor` tilecode in the back layer of custom levels seems to mostly work as expected with CustomTheme. This PR
- adds `set_storage_layer(LAYER)` to patch a function that normally only searches the back layer for storage items. Well I hope that's all the function does...
- exposes `state.storage_uid` to enable/disable storage floor per level.
```lua
-- Spawn normal storage floor and set storage layer if waddler is happy, otherwise the floor to the left of this tile
set_post_tile_code_callback(function(x, y, layer)
if not test_flag(state.quest_flags, 10) then
set_storage_layer(layer)
else
local floor = get_entity(get_grid_entity_at(x, y, layer))
if floor then
floor:destroy()
end
if get_grid_entity_at(x - 1, y, layer) ~= -1 then
local left = …
```
> Use storage floor in both layers, expose storage_uid

- src/game_api/script/lua_vm.cpp
This should be better and not fire all the time randomly. 500M instructions twice on the same frame to trigger, instead of 1B ever as it was before apparently.
> Fix infinite loop detection

- .github/workflows/whip-build.yml
- README.md
- src/injector/main.cpp
I was just thinking of implementing an auto updater and came up with this. (So copied mostly from some chinese example, didn't even read most of it.)
- Added the exe and dll to the whip release assets so they can be downloaded separately
- Launcher checks for newer whip release from github (with winapi) and downloads a new dll if updated
- Launcher saves the modified header to a file to compare against next time
- Asks if you want to enable updates and update when a new one is found
- Disabled for stable releases and local builds
Doing http requests to dll files probably does increase AV false positives though 😿
> Auto updater

- src/game_api/window_api.cpp
- src/injected/ui.cpp
Apparently the d3d vtable hooks crash with steam overlay when using the viewports stuff, because steam overlay already had them hooked, so I hooked the steam overlay instead.
(As a side effect this enables the option to hide OL from OBS game capture if running on steam.)
> Steam Overlay

- src/injected/CMakeLists.txt
- src/injected/ui.cpp
These are random default Windows 10 or 7 fonts. I guess playlunky should copy this.
> Add ui fonts for all supported game languages

- src/game_api/level_api.cpp
- src/game_api/script/lua_vm.cpp
- src/game_api/spawn_api.cpp
- src/game_api/spawn_api.hpp
- src/game_api/state_structs.hpp
When impostor lake entities are moved, it only moves the blue rendering. This change adds a method to fix the positions of impostor lake water physics boxes to match the positions of the entities.
> Add a method to fix impostor lake positions to match the positions of the entities.

- src/game_api/script/usertypes/hitbox_lua.cpp
the y axis in this game is backwards, so the math has to be flipped.
> Fix hitbox extrude parameter to use correct modification of y-coordinate.

- src/game_api/steam_api.cpp
- src/game_api/steam_api.hpp
- src/injected/ui.cpp
Adds checkboxes under Savegame menu to see and edit Steam achievements directly so you can at least try to undo the damage done by not blocking them in the first place, or I guess cheat if you want to, I'm not your mom.
> Edit Steam achievements

- src/game_api/script/lua_backend.cpp
- src/game_api/script/lua_backend.hpp
- src/game_api/script/lua_vm.cpp
Currently if you call save_script or save_progress from a callback that runs after ON.SAVE it will update your last_save time but not actually run the ON.SAVE callback.
This moves ON.SAVE callbacks into their own vector that always run last so manual saves work from any other callbacks.
> Move ON.SAVE callbacks to run last.

- docs/examples/RenderInfo.md
- docs/game_data/spel2.lua
- docs/parse_source.py
- src/game_api/render_api.cpp
- src/game_api/render_api.hpp
- src/game_api/script/usertypes/entity_lua.cpp
Added and exposed RenderInfo stuff to lua API to make it possible to use custom normal maps
Also edited autodoc parser a bit
> Renderinfo stuff

- README.md
- src/game_api/custom_types.cpp
- src/game_api/entities_logical.hpp
- src/game_api/flags.hpp
- src/game_api/movable.hpp
- src/game_api/rpc.cpp
- src/game_api/rpc.hpp
- src/game_api/script.cpp
- src/game_api/script.hpp
- src/game_api/script/lua_vm.cpp
- src/game_api/script/script_impl.cpp
- src/game_api/script/script_impl.hpp
- src/game_api/search.cpp
- src/game_api/window_api.cpp
- src/game_api/window_api.hpp
- src/injected/main.cpp
- src/injected/ui.cpp
- src/injector/main.cpp
- Random UI fixes
- Expose `update_state()` to run the game logic really fast, maybe to skip forward in a TAS or double the game speed
- Add `set_frametime()` to change the target engine fps, capped by gpu/monitor/vsync/whatever still
```lua
-- skip hundun rise in a few seconds, simulating everything in between but not wasting time to render it
while state.time_level < 5000 do
update_state()
end
-- run game at double speed, but keep timer at normal speed
set_callback(function()
if not no_repeat then
no_repeat = true
update_state()
state.time_level = state.time_level - 1
state.time_total = state.time_total - 1
no_repeat = nil
end
end, ON.POST_UPDATE)
-- run at 50% speed by changing frametime
set_frametime(1/30)
-- don't cap fps when window is unfocused
set_frametime_unfocused(0)
```
> Random UI things

- src/game_api/game_patches.cpp
- src/game_api/game_patches.hpp
- src/game_api/search.cpp
- src/game_api/state.cpp
- Patches spawning more than 4400 liquid by simply removing some old stale liquid instead of doing nothing like a Spelunky 2 dev
- Removes the neobab 4-2  error when (Randomizer) accidentally spawns more than 100 ushabti
> More patches

- docs/game_data/spel2.lua
- docs/generate_emmylua.py
Add `---@meta` to spel2.lua, wich indicates the language server that it is a definition file, making the multiple function declarations to work correctly
https://luals.github.io/wiki/annotations/#meta
> fix spel2.lua function overloads

- docs/game_data/spel2.lua
- docs/src/includes/_globals.md
- examples/barrymod.lua
- src/game_api/rpc.cpp
- src/game_api/rpc.hpp
- src/game_api/script/events.cpp
- src/game_api/script/lua_vm.cpp
- src/game_api/search.cpp
- src/injected/ui.cpp
- src/injected/ui_util.cpp
- src/injected/ui_util.hpp
Estebanfer just dropped this feature in the Discord, I only added API, UI and some checks...
- `save_state(slot)` Save current level state to slot 1..4
- `load_state(slot)` Load saved slot
- `StateMemory* get_save_state(slot)` 1..5
I believe these state copies are invalid after unloading the current level (at least loading from next level just crashed a lot), but not cleared, so I added a thing to invalidate them on level unload. Death screen is automatically cleared if loading from UI, but I'm not even sure if that's already messing with fate too much, or should it be part of the api too...
> Save states I guess

- src/game_api/script/lua_console.cpp
- src/game_api/script/script_util.cpp
- src/game_api/script/script_util.hpp
Originally it was a copy of `ImGui::InputText` from [imgui_stdlib.cpp](https://github.com/ocornut/imgui/blob/master/misc/cpp/imgui_stdlib.cpp#L47-L57) and used to call the ImGui C function, but on the commit below, it started calling the function it was copied from, without removing the the previous code, making the assert to fail on debug and executing some unnecessary code
https://github.com/spelunky-fyi/overlunky/commit/3b70edc64918a5cf47f23acaf161b9ec29865d7f#diff-1da18dbcb5bae1fe88bb2854c55ac61aa27b5afe3204a14fc975ad31460bc1c1R173
- The `dump_string` function wasn't being called protected, crashing the game if there was an error on it
- The current backend also wasn't getting pushed, so when `dump_string` tried to get an entity's user data, it couldn't get the backend and crashed …
> Some fixes

- docs/game_data/spel2.lua
- docs/parse_source.py
- docs/src/includes/_enums.md
- docs/src/includes/_globals.md
- docs/src/includes/_types.md
- examples/imguiio.lua
- src/game_api/aliases.hpp
- src/game_api/bucket.cpp
- src/game_api/bucket.hpp
- src/game_api/hook_handler.hpp
- src/game_api/script/lua_backend.cpp
- src/game_api/script/lua_backend.hpp
- src/game_api/script/lua_vm.cpp
- src/game_api/script/usertypes/bucket_lua.cpp
- src/game_api/script/usertypes/gui_lua.cpp
- src/game_api/script/usertypes/gui_lua.hpp
- src/game_api/state.cpp
- src/game_api/state.hpp
- src/game_api/window_api.cpp
- src/injected/ui.cpp
- Fixed most of the issues with OL and PL inputs clashing and doing stuff in both. OL now ignores keyboard / mouse input when PL is typing / hovering UI
- Also fixed `ImGuiIO.wantkeyboard` to disable input in the other tool
- Added `set_hotkey(fun(chord), KEY chord, HOTKEY_TYPE flags)` to hook keys though global windows hotkeys, which should once and for all skip all game input and other UI input
- Added `GuiDrawContext:key_picker(string message, KEY_TYPE flags)` to capture any key easily
- Added some more input functions and documentation to `ImGuiIO`
> Hotkeys and cross tool input fixes

- src/game_api/level_api.cpp
HDMod was having big issues with level loading times, turns out it was due to script procedural chances still being run when they were set to zero, with this change, average level loading changes got ~5x times better on it. It should be around the same on most small scripts.
Also, should I make the same change to community chances? I guess it would make sense
> Skip script chance logic providers if their spawn chance is zero

- .github/workflows/continous_integration.yml
- .github/workflows/whip-build.yml
- CMakeLists.txt
- src/game_api/script/lua_backend.cpp
- src/game_api/sound_manager.cpp
- src/shared/logger.h
Fixed latest MSVC build crashing when it injects to spelunky (the MSVC version now used for playlunky autobuild)
Fixed warning [-Wdeprecated-this-capture](https://www.emmtrix.com/wiki/Clang:Diag/warn_deprecated_this_capture)
> fix MSVC 19.40 build crashing, fix clangd warnings

- docs/game_data/spel2.lua
- docs/generate_emmylua.py
- docs/parse_source.py
- docs/src/includes/_globals.md
- examples/liquids.lua
- src/game_api/aliases.hpp
- src/game_api/rpc.cpp
- src/game_api/rpc.hpp
- src/game_api/script/lua_vm.cpp
- src/game_api/state_structs.hpp
I added the `ENTITY_MASK` enum, I didn't if name it `MASK` because sounds too much of a generic name, but if someone thinks it's fine then I'll change it
> Add get_liquids_at function and small stuff

- docs/generate.py
- docs/src/includes/_globals.md
Mentioned on discord
I guessed there was some intend to format the deprecated functions differently, so I made it consistent
> Fix the slight inconsistency of the `Deprecated functions` in the doc

- src/injected/ui.cpp
Currently when you go to back layer and switch "Light dark levels and layers" on and the off thru the UI, the illumination stays in the back layer
> Fix option `Light dark levels and layers` not returning the level illumination to normal after switching it in the UI

- src/injected/ui.cpp
- don't force `lock_input_timer` to 0 every frame
- fix the floating in the air when fallen into item spikes (movable spikes on hundun platform)
Fixes #381
`lock_input_timer` is also used by the tentacles at the bottom of tiamat and abzu to lock you out of controls before dropping into the abyss. Thou i don't think it's that big of a deal
> Godmode fix

- src/game_api/script/lua_backend.cpp
- src/game_api/script/lua_backend.hpp
- src/game_api/script/safe_cb.inl
Daft because i didn't test if there are possible situations when the calls to `set_current_callback` and `clear_current_callback` are uneven
> Fix current callback being overwritten if another one starts before the first one finished execution
